# Model library

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, results="asis")
options(kableExtra_view_html=FALSE) # Needed otherwise tables appear in Viewer only (not in html files)
# See https://github.com/haozhu233/kableExtra/issues/455
```

```{r}
library(campsis)

getPKDescription <- function(x) {
  structuralModel <- ""
  if (grepl("1cpt", x=x)) {
    structuralModel <- "One-compartment PK model"
  } else if (grepl("2cpt", x=x)) {
    structuralModel <- "Two-compartment PK model"
  } else if (grepl("3cpt", x=x)) {
    structuralModel <- "Three-compartment PK model"
  }
  
  firstOrder <- ""
  if (grepl("fo", x=x)) {
    firstOrder <- "with first-order absorption"
  }
  
  zeroOrder <- ""
  if (grepl("zo", x=x)) {
    zeroOrder <- "with zero-order absorption"
  }
  
  mmAbs <- ""
  if (grepl("mmabs", x=x)) {
    zeroOrder <- "with Michaelis-Menten absorption"
  }
  
  weibull <- ""
  if (grepl("weibull_double", x=x)) {
    weibull <- "with double Weibull absorption (GAM1, GAM2)"
  } else if (grepl("weibull_original", x=x)) {
    weibull <- "with Weibull absorption (TAU, SH)"
  } else if (grepl("weibull", x=x)) {
    weibull <- "with Weibull absorption (GAM)"
  }
  
  lag <- ""
  if (grepl("lag", x=x)) {
    lag <- " (+ lag time)"
  } else if (grepl("transit", x=x)) {
    lag <- " (+ transit compartments)"
  }
  
  elimination <- ""
  if (grepl("mixed", x=x)) {
    elimination <- "and mixed elimination"
  } else if (grepl("mm", x=x)) {
    elimination <- "and Michaelis-Menten elimination"
  } else {
    elimination <- "and linear elimination"
  }
  
  return(paste0(structuralModel, " ", firstOrder, zeroOrder, weibull, lag, " ", elimination))
}

getTMDDDescription <- function(x) {
  dispoModel <- ""
  if (grepl("1cpt", x=x)) {
    dispoModel <- "one-compartment disposition model"
  } else if (grepl("2cpt", x=x)) {
    dispoModel <- "two-compartment disposition model"
  } else if (grepl("3cpt", x=x)) {
    dispoModel <- "three-compartment disposition model"
  }
  
  firstOrder <- ""
  if (grepl("fo", x=x)) {
    firstOrder <- "with first-order absorption"
  }
  
  zeroOrder <- ""
  if (grepl("zo", x=x)) {
    zeroOrder <- "with zero-order absorption"
  }

  type <- ""
  if (grepl("full_cst_rtot_ib", x=x)) {
    type <- "Full TMDD model with constant receptor concentration and irreversible binding"
  } else if (grepl("full_cst_rtot", x=x)) {
    type <- "Full TMDD model with constant receptor concentration"
  } else if (grepl("full_ib", x=x)) {
    type <- "Full TMDD model with irreversible binding"
  } else if (grepl("full", x=x)) {
    type <- "Full TMDD model"
  } else if (grepl("qe", x=x)) {
    type <- "Quasi-Equilibrium (QE) TMDD model"
  } else if (grepl("qss", x=x)) {
    type <- "Quasi steady-state (QSS) TMDD model"
  } else if (grepl("wagner", x=x)) {
    type <- "Wagner TMDD model"
  }

  return(paste0(type, " including ", dispoModel, " ", firstOrder, zeroOrder))
}

getNONMEMDescription <- function(x) {
  desc <- ""
  if (x=="advan1_trans1") {
    desc <- "One-compartment PK model with zero-order absorption (K, V)"
  } else if (x=="advan1_trans2") {
    desc <- "One-compartment PK model with zero-order absorption (CL, V)"
  } else if (x=="advan2_trans1") {
    desc <- "One-compartment PK model with first-order absorption (KA, K, V)"
  } else if (x=="advan2_trans2") {
    desc <- "One-compartment PK model with first-order absorption (KA, CL, V)"
  } else if (x=="advan3_trans1") {
    desc <- "Two-compartment PK model with zero-order absorption (K, V, K12, K21)"
  } else if (x=="advan3_trans3") {
    desc <- "Two-compartment PK model with zero-order absorption (CL, V, Q, VSS)"
  } else if (x=="advan3_trans4") {
    desc <- "Two-compartment PK model with zero-order absorption (CL, V1, V2, Q)"
  } else if (x=="advan3_trans5") {
    desc <- "Two-compartment PK model with zero-order absorption (AOB, ALPHA, BETA)"
  } else if (x=="advan4_trans1") {
    desc <- "Two-compartment PK model with first-order absorption (KA, K, V, K23, K32)"
  } else if (x=="advan4_trans3") {
    desc <- "Two-compartment PK model with first-order absorption (KA, CL, V, Q, VSS)"
  } else if (x=="advan4_trans4") {
    desc <- "Two-compartment PK model with first-order absorption (KA, CL, V2, V3, Q)"
  } else if (x=="advan4_trans5") {
    desc <- "Two-compartment PK model with first-order absorption (KA, AOB, ALPHA, BETA)"
  } else if (x=="advan11_trans4") {
    desc <- "Three-compartment PK model with zero-order absorption (CL, V1, V2, V3, Q2, Q3)"
  } else if (x=="advan12_trans4") {
    desc <- "Three-compartment PK model with first-order absorption (KA, CL, V1, V2, V3, Q2, Q3)"
  }
  return(desc)
}

getThetas <- function(model, no_label=FALSE, no_unit=FALSE) {
  thetas <- model@parameters@list %>%
    purrr::keep(~is(.x, "theta")) %>%
    purrr::map_dfr(~campsismod:::as.data.frame(.x, row.names="", optional=FALSE)) %>%
    dplyr::select(-c("index", "min", "max", "fix", "comment")) %>%
    dplyr::rename(Name=name, Value=value, Label=label, Unit=unit) %>%
    dplyr::mutate(Unit=dplyr::if_else(is.na(Unit), "", Unit))
  if (no_label) {
    thetas <- thetas %>%
      dplyr::select(-Label)
  }
  if (no_unit) {
    thetas <- thetas %>%
      dplyr::select(-Unit)
  }
  return(thetas)
}

printModelSummary <- function(description, thetas, ode) {
  odeCapture <- gsub(pattern="\\*", replacement="\\\\*", x=paste0(capture.output(print(ode))[-1], collapse="<BR>"))
  
  cat("###", name, "\n")
  cat("**Description**:", description, "\n\n")
  cat("**Parameter table**:", "\n\n")
  kbl <- kableExtra::kbl(thetas, booktabs=T, format="html") %>%
    kableExtra::kable_styling(full_width=F) %>%
    kableExtra::column_spec(1, width = "2cm") %>%
    kableExtra::column_spec(2, width = "2cm")
  if ("Label" %in% colnames(thetas)) {
    kbl <- kbl %>%
      kableExtra::column_spec(3, width = "10cm")
  }
  if ("Unit" %in% colnames(thetas)) {
    kbl <- kbl %>% 
    kableExtra::column_spec(4, width = "2cm")
  }
  print(kbl)
  cat("\n")
  cat("**ODEs**:", "\n\n")
  cat(odeCapture, "\n")
  cat("\n")
}

```

## PK section

```{r, results='asis'}
pks <- ecampsis::e_model_suite$pk

for (name in names(pks)) {
  model <- pks[[name]]
  description <- getPKDescription(name)
  thetas <- getThetas(model)
  ode <- model %>% find(OdeRecord())
  printModelSummary(description, thetas, ode)
}
```

## TMDD section

```{r, results='asis'}
tmdds <- ecampsis::e_model_suite$tmdd

for (name in names(tmdds)) {
  model <- tmdds[[name]]
  description <- getTMDDDescription(name)
  thetas <- getThetas(model)
  ode <- model %>% find(OdeRecord())
  printModelSummary(description, thetas, ode)
}
```

## NONMEM section

```{r, results='asis'}
nonmems <- ecampsis::e_model_suite$nonmem

for (name in names(nonmems)) {
  model <- nonmems[[name]]
  description <- getNONMEMDescription(name)
  thetas <- getThetas(model, no_label=TRUE, no_unit=TRUE)
  ode <- model %>% find(OdeRecord())
  printModelSummary(description, thetas, ode)
}
```
