# Post-processing

Perform post-processing calculations, for example apply non-compartmental methods to derive key PK parameters.

The steps are:

* add the metrics you are interested in (e.g., AUC, Cmax and tmax),
* if relevant, stratify by SCENARIO, ARM and/or PERIOD
* click refresh grid 
* click the button 'Apply to all panels'
* click on the Calculate button !

Description of the options:

* Periods: define the periods to select the time range included for calculation of the metrics
* New metric: select the metric and the output to which the metric should be calculated on, define the time range or select one of the periods defined. A label can be defined. If period is selected, PERIOD has to be selected as a stratification factor
* Available metrics: the metrics created are shown in this box
* Edit zone: click on a metric and dragged it to this zone to edit it
* Drop zone: if a metric had to be remove from one of the stratification, click-and-drop to this zone
* Refresh grid: to reset boxes (on the right)

